update russian
colobot/colobot pull request #1396
Opened 2021-02-28 16:59 UTC by DavydovMA

add:
	new file:   desktop/po/ru.po
update:
	modified:   po/ru.po

2021-07-13 06:49 UTC, AndreiCherniaev requested changes
Манускрипт необходимо доработать согласно замечаниям рецензента.

2021-07-13 06:49 UTC, AndreiCherniaev commented on desktop/po/ru.po
> +"язык, CBOT, похожий на C++ и Java-like, который можно использовать для "
Не существует языка Java-like!

2021-07-13 06:49 UTC, AndreiCherniaev commented on desktop/po/ru.po
> +"обучение программированию с помощью развлечения. Вы играете за космонавта "
За космонавта ЗАПЯТАЯ путешествующего

2021-07-13 06:49 UTC, AndreiCherniaev commented on desktop/po/ru.po
> +msgstr "Установить путь к каталогу сохранения (требуется доступ по записи)"
По записи доступ в МФЦ или некоторые поликлиники... А здесь же - доступ на запись.

2021-07-13 06:49 UTC, AndreiCherniaev commented on desktop/po/ru.po
> +msgstr "Установить уровень журнала."
Большие сомнения в корректности перевода... Скорее всего здесь речь о степени подробности журнала...

2021-07-24 08:43 UTC, DavydovMA commented on desktop/po/ru.po
> +"язык, CBOT, похожий на C++ и Java-like, который можно использовать для "
colobot и colobot-data - слишком большое время отклика (latency), проект уже остыл. Это GPL - забирайте то что есть и набор напильников в руки. С наилучшими пожеланиями, удачи.

2021-07-24 08:43 UTC, DavydovMA commented on desktop/po/ru.po
> +"обучение программированию с помощью развлечения. Вы играете за космонавта "
colobot и colobot-data - слишком большое время отклика (latency), проект уже остыл. Это GPL - забирайте то что есть и набор напильников в руки. С наилучшими пожеланиями, удачи.

2021-07-24 08:44 UTC, DavydovMA commented on desktop/po/ru.po
> +msgstr "Установить путь к каталогу сохранения (требуется доступ по записи)"
colobot и colobot-data - слишком большое время отклика (latency), проект уже остыл. Это GPL - забирайте то что есть и набор напильников в руки. С наилучшими пожеланиями, удачи.

2021-07-24 08:44 UTC, DavydovMA commented on desktop/po/ru.po
> +msgstr "Установить уровень журнала."
colobot и colobot-data - слишком большое время отклика (latency), проект уже остыл. Это GPL - забирайте то что есть и набор напильников в руки. С наилучшими пожеланиями, удачи.

2021-09-06 20:05 UTC, MrSimbax commented
Please use English when commenting pull requests, as there are currently no maintainers who know Russian.

> colobot и colobot-data - слишком большое время отклика (latency), проект уже остыл. Это GPL - забирайте то что есть и набор напильников в руки. С наилучшими пожеланиями, удачи.

From Google Translate:
> colobot and colobot-data - latency is too long, the project has already cooled down. This is the GPL - take what you have and a set of files in your hands. Best wishes, good luck. 

So I assume the author gave up after waiting too long for the pull request to be reviewed. Shame, as it seems I have to close this :( None of the maintainers know Russian well enough to read and/or fix those changes, the author doesn't want to make changes after review and there are conflicting files now. I am also closing https://github.com/colobot/colobot-data/pull/52 for the same reasons. Really unfortunate. Maybe this PR will at least help somebody else as a base for new PR.

2021-09-06 20:05 UTC, closed without merging

2021-09-07 10:50 UTC, AndreiCherniaev commented
> Please use English when commenting pull requests, as there are currently no maintainers who know Russian.
> 
> > colobot и colobot-data - слишком большое время отклика (latency), проект уже остыл. Это GPL - забирайте то что есть и набор напильников в руки. С наилучшими пожеланиями, удачи.
> 
> From Google Translate:
> 
> > colobot and colobot-data - latency is too long, the project has already cooled down. This is the GPL - take what you have and a set of files in your hands. Best wishes, good luck.
> 
> So I assume the author gave up after waiting too long for the pull request to be reviewed. Shame, as it seems I have to close this :( None of the maintainers know Russian well enough to read and/or fix those changes, the author doesn't want to make changes after review and there are conflicting files now. I am also closing [colobot/colobot-data#52](https://github.com/colobot/colobot-data/pull/52) for the same reasons. Really unfortunate. Maybe this PR will at least help somebody else as a base for new PR.

Bad news.

Colobot Gold has got big russian community... https://m.youtube.com/watch?v=E_kVC32OVTI

2021-09-07 14:13 UTC, tomangelo2 commented
It's not like we don't want to update russian translations. This pull request had requested changes, that no one did, also file conflicts appeared. Since we can't fix it manually by ourselves, we had to close it to not leave pulls in permanent hibernation. If someone is willing to fix the translations, we could work something out, like reopen this pull request, or maybe someone will make another one.