Russian translate
colobot/colobot pull request #1470
Opened 2021-11-06 06:37 UTC by zvladru

Just some improvements to russian translation

2021-12-02 14:31 UTC, X64E commented on po/ru.po
> +msgstr "Быстрая загрузка\\Быстрыа загрузка сохраненной игры"
Быстрыа загрузка?

2021-12-02 14:34 UTC, X64E requested changes
Only one typo finded.

2021-12-02 14:34 UTC, X64E commented on po/ru.po
> +msgstr "Быстрая загрузка\\Быстрыа загрузка сохраненной игры"
"Быстрыа" must be -> "Быстрая"

2021-12-04 08:51 UTC, MrSimbax requested changes
Please fix the typo mentioned earlier and change the target branch to `dev`.

> I think this pull can be moved to https://github.com/colobot/colobot-data/pulls

It cannot, these translations are needed by the binary for UI etc. and so the file is in the main repo.

2021-12-06 16:03 UTC, X64E requested changes

2021-12-06 16:03 UTC, X64E commented on po/ru.po
> +msgstr "Нет закрывающих кавычек"
Пропущена закрывающая кавычка

2021-12-06 16:03 UTC, X64E commented on po/ru.po
> +msgstr "Музыка:\\Громкость музыки"
Фоновая музыка:\\Громкость фоновой музыки

2022-07-25 12:06 UTC, Anton-V-K commented on po/ru.po
> +msgstr "Вниз\\Переместить мод вниз в списке загрузки, он будет загружен позже(мод может переписать файлы после модов загруженных перед ним)"
Пробел перед открывающей скобкой?
The part in braces may be translated this way "(моды могут переписать файлы модов, расположенных в списке выше них)"

2022-07-25 12:07 UTC, Anton-V-K commented on po/ru.po
> +msgstr "Функции требуется возратить тип \"void\"
"Функция должна возвращать тип \\"void\\"**"**
Note that extra quote is needed at the end

2022-07-25 12:11 UTC, Anton-V-K commented on po/ru.po
> +msgstr "Изменения:"
Is the colon appropriate here?

2022-07-25 12:19 UTC, Anton-V-K commented on po/ru.po
> +msgstr "Отключить\\Отключить выборанный мод"
"Отключить\\Отключить выбранный мод" (extra "о" is to be removed)

2022-07-25 12:22 UTC, Anton-V-K commented on po/ru.po
> +msgstr "Дублировать метку на переключателе"
This is the message for `CBotErrRedefCase`, so I guess it should be translated other way like ""Повторная метка в \\"switch\\""

2022-07-25 12:24 UTC, Anton-V-K commented on po/ru.po
> +msgstr "Построить убежище"
Though "vault" is translated as "убежище" in this file, in some standard missions it is translated as "погреб".

2022-07-25 12:27 UTC, Anton-V-K commented on po/ru.po
> +msgstr "Начать исследование программы для мишени"
"Начать исследование программы для **бота**-мишени"

2022-07-25 12:29 UTC, Anton-V-K commented on po/ru.po
> +msgstr "Адрес %s не может быть открыть в баузере"
"Адрес %s не может быть открыть в б**р**аузере" (missing "р")

2022-07-25 12:30 UTC, Anton-V-K commented on po/ru.po
> +msgstr "Путь /% не может быть открыть в проводнике"
"Путь **%s** не может быть открыть в проводнике" ("%s" should be used)

2022-07-25 12:30 UTC, Anton-V-K commented on po/ru.po
> +msgstr "Гусенечный строитель"
"Гусен**и**чный строитель" ("и" instead of "е")

2022-07-25 12:31 UTC, Anton-V-K commented on po/ru.po
> +msgstr "Вверх\\Переместить мод вверх в списке загрузки, он будет загружен раньше(моды ниже могут переписать файлы после модов загруженных ранее)"
Extra space before opening brace?
The part in braces may be translated this way "(моды могут переписать файлы модов, расположенных в списке выше них)"

2022-07-25 12:35 UTC, Anton-V-K commented on po/ru.po
> +msgstr "Вертикальная синхронизация\\Ограничевает число кадров в секунду частотой экрана"
"Огранич**и**вает" ("и" вместо "е")

2022-11-02 10:23 UTC, Emxx52 approved these changes

2022-11-02 10:27 UTC, merged