Improved parsing tokens
colobot/colobot pull request #1762
Opened 2024-08-28 06:33 UTC by melex750

2024-08-28 07:24 UTC, hexagonrecursion commented on CBot/src/CBot/CBotUtils.h
> +static inline void UpdateCRC32(const unsigned char c, uint32_t& check)
```suggestion
static inline void UpdateCRC32(unsigned char c, uint32_t& check)
```

2024-08-28 07:50 UTC, melex750 commented on CBot/src/CBot/CBotUtils.h
> +static inline void UpdateCRC32(const unsigned char c, uint32_t& check)
Its left over from when I tried passing a reference there.

2024-08-28 09:24 UTC, hexagonrecursion requested changes

2024-08-28 09:33 UTC, melex750 commented on CBot/src/CBot/CBotUtils.h
> +static inline void UpdateCRC32(const unsigned char c, uint32_t& check)
Oops, another left over keyword. 😬

2024-08-28 10:17 UTC, melex750 commented on CBot/src/CBot/CBotToken.h
> +    uint32_t        signature{0};
```CBotProgram::RestoreState()``` already starts the program from the beginning if restoring the stack fails. We can do this also if we detect that the cbot code has changed between save and restore.

2024-08-28 10:25 UTC, melex750 commented on CBot/src/CBot/CBotToken.cpp
>      char c = *(program++);                 // next character
next octet of booleans :laughing:

2024-08-28 10:33 UTC, melex750 commented on CBot/src/CBot/CBotToken.cpp
> +    return c == 0 || c == '\t' || c == '\n' || c == '\r';
That's how they were before, i didn't change it.  Maybe it's a good thing; ```\t``` might easier recognize as a tab when you're actually looking at the text.

2024-08-28 10:41 UTC, melex750 commented on CBot/src/CBot/CBotToken.cpp
>          if (token[0] == '\"' )
I add a check for token empty like it had before. But I think it's ok if CompileTokens() expects valid utf-8, we can check a string before sending it to CompileTokens().

2024-10-20 17:09 UTC, melex750 commented
Made changes suggested in review and resolved conflicts with ```dev```.

2024-10-20 17:10 UTC, melex750 commented on CBot/src/CBot/CBotToken.h
> +    size_t          currentColumnIndex{0};
Maybe something like ```struct CBotCodeStats``` with line count, checksum, etc.

2024-10-22 05:03 UTC, hexagonrecursion approved these changes
Looks good to me

2024-12-09 17:05 UTC, merged