Improved warning dialog
colobot/colobot pull request #1820
Opened 2024-12-19 02:27 UTC by melex750

Added ability to scroll, select, and copy text in the warning dialog.  Allowing for more verbose/helpful error messages.

P.S. Level parser exceptions are displayed in this dialog.

2024-12-19 11:38 UTC, hexagonrecursion requested changes
Why only for warnings? Why not make CMainDialog::StartInformation() always use CreateEdit?

2024-12-19 12:57 UTC, melex750 commented
> Why only for warnings? Why not make CMainDialog::StartInformation() always use CreateEdit?

The main reason is CLabel centers the text by default and I didn't mess up the other things that might rely on that.

2024-12-19 19:41 UTC, hexagonrecursion approved these changes

2025-01-05 18:57 UTC, tomangelo2 approved these changes

2025-01-05 18:57 UTC, merged